// Copyright (c) 2020-2023 InSeven Limited
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import SwiftUI

extension Array where Element == Color {

    static let html: [Color] = [
        .HTML.aliceBlue,
        .HTML.antiqueWhite,
        .HTML.aqua,
        .HTML.aquamarine,
        .HTML.azure,
        .HTML.beige,
        .HTML.bisque,
        .HTML.black,
        .HTML.blanchedAlmond,
        .HTML.blue,
        .HTML.blueViolet,
        .HTML.brown,
        .HTML.burlyWood,
        .HTML.cadetBlue,
        .HTML.chartreuse,
        .HTML.chocolate,
        .HTML.coral,
        .HTML.cornflowerBlue,
        .HTML.cornsilk,
        .HTML.crimson,
        .HTML.cyan,
        .HTML.darkBlue,
        .HTML.darkCyan,
        .HTML.darkGoldenRod,
        .HTML.darkGray,
        .HTML.darkGrey,
        .HTML.darkGreen,
        .HTML.darkKhaki,
        .HTML.darkMagenta,
        .HTML.darkOliveGreen,
        .HTML.darkOrange,
        .HTML.darkOrchid,
        .HTML.darkRed,
        .HTML.darkSalmon,
        .HTML.darkSeaGreen,
        .HTML.darkSlateBlue,
        .HTML.darkSlateGray,
        .HTML.darkSlateGrey,
        .HTML.darkTurquoise,
        .HTML.darkViolet,
        .HTML.deepPink,
        .HTML.deepSkyBlue,
        .HTML.dimGray,
        .HTML.dimGrey,
        .HTML.dodgerBlue,
        .HTML.fireBrick,
        .HTML.floralWhite,
        .HTML.forestGreen,
        .HTML.fuchsia,
        .HTML.gainsboro,
        .HTML.ghostWhite,
        .HTML.gold,
        .HTML.goldenRod,
        .HTML.gray,
        .HTML.grey,
        .HTML.green,
        .HTML.greenYellow,
        .HTML.honeyDew,
        .HTML.hotPink,
        .HTML.indianRed,
        .HTML.indigo,
        .HTML.ivory,
        .HTML.khaki,
        .HTML.lavender,
        .HTML.lavenderBlush,
        .HTML.lawnGreen,
        .HTML.lemonChiffon,
        .HTML.lightBlue,
        .HTML.lightCoral,
        .HTML.lightCyan,
        .HTML.lightGoldenRodYellow,
        .HTML.lightGray,
        .HTML.lightGrey,
        .HTML.lightGreen,
        .HTML.lightPink,
        .HTML.lightSalmon,
        .HTML.lightSeaGreen,
        .HTML.lightSkyBlue,
        .HTML.lightSlateGray,
        .HTML.lightSlateGrey,
        .HTML.lightSteelBlue,
        .HTML.lightYellow,
        .HTML.lime,
        .HTML.limeGreen,
        .HTML.linen,
        .HTML.magenta,
        .HTML.maroon,
        .HTML.mediumAquaMarine,
        .HTML.mediumBlue,
        .HTML.mediumOrchid,
        .HTML.mediumPurple,
        .HTML.mediumSeaGreen,
        .HTML.mediumSlateBlue,
        .HTML.mediumSpringGreen,
        .HTML.mediumTurquoise,
        .HTML.mediumVioletRed,
        .HTML.midnightBlue,
        .HTML.mintCream,
        .HTML.mistyRose,
        .HTML.moccasin,
        .HTML.navajoWhite,
        .HTML.navy,
        .HTML.oldLace,
        .HTML.olive,
        .HTML.oliveDrab,
        .HTML.orange,
        .HTML.orangeRed,
        .HTML.orchid,
        .HTML.paleGoldenRod,
        .HTML.paleGreen,
        .HTML.paleTurquoise,
        .HTML.paleVioletRed,
        .HTML.papayaWhip,
        .HTML.peachPuff,
        .HTML.peru,
        .HTML.pink,
        .HTML.plum,
        .HTML.powderBlue,
        .HTML.purple,
        .HTML.rebeccaPurple,
        .HTML.red,
        .HTML.rosyBrown,
        .HTML.royalBlue,
        .HTML.saddleBrown,
        .HTML.salmon,
        .HTML.sandyBrown,
        .HTML.seaGreen,
        .HTML.seaShell,
        .HTML.sienna,
        .HTML.silver,
        .HTML.skyBlue,
        .HTML.slateBlue,
        .HTML.slateGray,
        .HTML.slateGrey,
        .HTML.snow,
        .HTML.springGreen,
        .HTML.steelBlue,
        .HTML.tan,
        .HTML.teal,
        .HTML.thistle,
        .HTML.tomato,
        .HTML.turquoise,
        .HTML.violet,
        .HTML.wheat,
        .HTML.white,
        .HTML.whiteSmoke,
        .HTML.yellow,
        .HTML.yellowGreen,
    ]

    static let tags: [Color] = {
        return html.filter { color in
            guard let gray = color.gray,
                  gray < 0.9,
                  gray > 0.1
            else {
                return false
            }
            return true
        }
    }()

}
