# Copyright (c) 2018-2021 InSeven Limited
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

skip_docs

lane :notarize_release do |options|
    notarize(
        package: options[:package],
        username: ENV['APPLE_DEVELOPER_ID'],
        verbose: true,
    )
end

lane :upload do |options|
    api_key = app_store_connect_api_key(
        key_id: options[:api_key_id],
        issuer_id: options[:api_key_issuer_id],
        key_filepath: options[:api_key],
        duration: 1200,
        in_house: false
    )
    upload_to_testflight(
        api_key: api_key,
        skip_submission: true,
        ipa: options[:ipa],
        pkg: options[:pkg],
        notify_external_testers: false,
        changelog: options[:changelog],
    )
end
