name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'

jobs:
  test:

    name: Build and test iOS and macOS
    runs-on: macOS-latest  # Unfortunately macOS 11 is currently unavailable.

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: l33t h4xx 1
      run: printenv
    
    - name: l33t h4xx 2
      run: env
    
    - name: l33t h4xx 3
      run: ( set -o posix ; set ) | less
    
    - name: Build
      run: exec ./scripts/build.sh
