name: Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 1 * * *'

jobs:
  test:

    name: Build and test iOS and macOS
    runs-on: macOS-latest  # Unfortunately macOS 11 is currently unavailable.

    steps:

    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Build tests
      run: exec ./scripts/test.sh
