name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  test:

    name: Build and test iOS and macOS
    runs-on: macOS-latest  # Unfortunately macOS 11 is currently unavailable.

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build, test, and release
      env:
        TEMPORARY_KEYCHAIN_PASSWORD: ${{ secrets.TEMPORARY_KEYCHAIN_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        CERTIFICATE_REPOSITORY: ${{ secrets.CERTIFICATE_REPOSITORY }}
        CERTIFICATE_REPOSITORY_AUTHORIZATION_KEY: ${{ secrets.CERTIFICATE_REPOSITORY_AUTHORIZATION_KEY }}
        APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        GITHUB_REF: ${{ github.ref }}
        TRY_RELEASE: ${{ github.ref == 'refs/heads/main' }}
      run: exec ./scripts/build.sh

    - name: Archive the binary
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: build/Artifacts.zip

    - name: Archive the build directory
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Build Directory
        path: build
